# From the project root: Rscript --vanilla obesity-shiny/checks/verify-assistant.R
if (dir.exists("apps/observatoire")) setwd("apps/observatoire") else if (dir.exists("obesity-shiny")) setwd("obesity-shiny")
source("app.R")
p <- assistant_normaliser(list(Classe="Obésité",Age=25,Activite="1-2 jours",Transport="Marche",Fast_food="inventé"),donnees_afdm)
stopifnot(!"Classe" %in% names(p),is.null(p$Fast_food),identical(p$Age,25L))
cat("PASS — Profil validé sans classe prédite ni valeur inventée\n")
x <- assistant_completer_explicite(list(),"Je fais du sport deux jours par semaine.",donnees_afdm)
stopifnot(identical(x$Activite,"1-2 jours"))
x <- assistant_completer_explicite(list(),"Je ne fais pas de sport mais je marche 2 jours par semaine.",donnees_afdm)
stopifnot(is.null(x$Activite))
cat("PASS — Vérification des déclarations numériques sans confusion avec la marche\n")
r <- assistant_comparer(list(Activite="1-2 jours",Transport="Marche"),donnees_afdm)
stopifnot(identical(r$n,36L),all(donnees_afdm$Activite[r$ids]=="1-2 jours"),all(donnees_afdm$Transport[r$ids]=="Marche"),sum(r$repartition$Effectif)==r$n,abs(sum(r$repartition$Part)-100)<1e-8,r$afficher_parts)
cat("PASS — Groupe de démonstration : 36 personnes, calcul exact\n")
r <- assistant_comparer(list(Age=80),donnees_afdm)
stopifnot(r$hors_age,r$n==0,!r$afficher_parts)
r <- assistant_comparer(list(Age=54,Activite="Aucune",Transport="Marche",Famille="Oui"),donnees_afdm)
stopifnot(!r$afficher_parts)
stopifnot(inherits(tryCatch(assistant_comparer(list(),donnees_afdm),error=identity),"error"))
cat("PASS — Âge hors échantillon, petits groupes et profil vide\n")
stopifnot(!assistant_explication_valide("Vous avez 80 % de risque."),!assistant_explication_valide("Vous êtes obèse."),!assistant_explication_valide("Vous devriez changer votre alimentation."),assistant_explication_valide("La comparaison décrit un groupe du fichier. Les autres caractéristiques peuvent différer. Une association ne démontre pas une causalité."))
cat("PASS — Explications chiffrées inventées ou prescriptives rejetées\n")
shiny::testServer(server, {
  session$setInputs(variable_modalites_public="Activite",modalite_focus_public="__toutes__",afficher_ellipses=TRUE,
    assistant_Age=NA_real_,assistant_Sexe="",assistant_Famille="",assistant_Fast_food="",assistant_Legumes="",assistant_Activite="1-2 jours",assistant_Technologie="",assistant_Transport="Marche")
  session$setInputs(assistant_comparer=1)
  stopifnot(identical(assistant$resultat()$n,36L),grepl("36 personnes",output$assistant_resultat$html))
  session$setInputs(assistant_vers_carte=1)
  stopifnot(length(assistant$selection_carte())==36)
  z <- jsonlite::fromJSON(output$carte_interactive,simplifyVector=FALSE)
  stopifnot(length(z$x$data)==13)
  session$setInputs(assistant_Activite="Aucune")
  stopifnot(is.null(assistant$resultat()),is.null(assistant$selection_carte()))
  session$setInputs(assistant_comparer=2)
  session$setInputs(assistant_question="Quel est mon risque de diabète ?",assistant_expliquer=1)
  stopifnot(grepl("ne permet pas d’estimer",output$assistant_dialogue$html))
  session$setInputs(assistant_effacer=1)
  stopifnot(is.null(assistant$resultat()),!assistant$busy())
})
cat("PASS — Confirmation, lien vers l’AFDM, résultats invalidés après modification, réponse aux questions de risque et effacement\n")
# Mock only the HTTP transport: never send a credential or profile externally.
completed <- FALSE
problem <- NULL
transport <- function(url,body,headers) {
  stopifnot(url=="https://api.openai.com/v1/responses",identical(body$store,FALSE),body$text$format$type=="json_schema")
  promises::promise_resolve(list(status="completed",output=list(list(type="message",content=list(list(type="output_text",text='{"Age":null}'))))))
}
promises::then(assistant_llm(list(ready=TRUE,provider="openai",model="gpt-5.4-mini"),"instructions","profil fictif",assistant_schema(donnees_afdm),transport=transport),onFulfilled=function(x){stopifnot(identical(x,'{"Age":null}'));completed<<-TRUE},onRejected=function(e){problem<<-conditionMessage(e);completed<<-TRUE})
while(!completed) later::run_now(timeoutSecs=0.1)
stopifnot(is.null(problem))
cat("PASS — Adaptateur OpenAI : sortie structurée et lecture de la réponse, sans appel réseau\n")
